# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183bfe4ab713f663cba131bff7c27d86e6352a32e25935ae9ff58bf437d739693138596061f77b6154ffdb196f7008fdf31b3531ee9fd9f545625b1f4860ef6a

test:
  secret_key_base: 23a41e6412f992f456cd51ae915b826c52e8f77e318994584587d6d2a8601129fcc68d1c3edb2410e2e69fb17b2bf41de26125722f34203ba4af4fdaf47f790a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
